if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_clangcl/tests/associative_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_clangcl/tests/associative_tests[1]_tests.cmake")
else()
  add_test(associative_tests_NOT_BUILT associative_tests_NOT_BUILT)
endif()
