if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_msvc/tests/golden_serialization_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_msvc/tests/golden_serialization_tests[1]_tests.cmake")
else()
  add_test(golden_serialization_tests_NOT_BUILT golden_serialization_tests_NOT_BUILT)
endif()
