if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_msvc2/tests/dispatch_property_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_msvc2/tests/dispatch_property_tests[1]_tests.cmake")
else()
  add_test(dispatch_property_tests_NOT_BUILT dispatch_property_tests_NOT_BUILT)
endif()
