if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_msvc2/tests/edge_case_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_ninja_msvc2/tests/edge_case_tests[1]_tests.cmake")
else()
  add_test(edge_case_tests_NOT_BUILT edge_case_tests_NOT_BUILT)
endif()
