if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_ci/tests/item_memory_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_ci/tests/item_memory_tests[1]_tests.cmake")
else()
  add_test(item_memory_tests_NOT_BUILT item_memory_tests_NOT_BUILT)
endif()
