if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_vs2022_x64/tests/backend_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_vs2022_x64/tests/backend_tests[1]_tests.cmake")
else()
  add_test(backend_tests_NOT_BUILT backend_tests_NOT_BUILT)
endif()
