if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_vs2022_x64/tests/config_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_vs2022_x64/tests/config_tests[1]_tests.cmake")
else()
  add_test(config_tests_NOT_BUILT config_tests_NOT_BUILT)
endif()
