if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_scalar/tests/numeric_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_scalar/tests/numeric_tests[1]_tests.cmake")
else()
  add_test(numeric_tests_NOT_BUILT numeric_tests_NOT_BUILT)
endif()
