if(EXISTS "C:/Users/cisco/Desktop/dev/research/HyperStream/build_capi/tests/wide_counter_smoke_tests[1]_tests.cmake")
  include("C:/Users/cisco/Desktop/dev/research/HyperStream/build_capi/tests/wide_counter_smoke_tests[1]_tests.cmake")
else()
  add_test(wide_counter_smoke_tests_NOT_BUILT wide_counter_smoke_tests_NOT_BUILT)
endif()
